### ISSUE TITLE
/removal IP-Form returns currently connected IP rather than the offended IP in database just typed into that form

### ISSUE THREAD

**Issue by ggaussling** [psilocyberunner/stop-forum-spam#2]
At stopforumspam.com/removal the Form at the buttom of that page returns the IP from which I'm connected to that page, rather than the IP I typed in, when filling out the form. Therefor it's impossible to remove an entry in the database that is requested unjust from an abusing forum admin, by NOT using the exact same IP-Address from that I formerly posted to that malicious forum, and so added to your SFS database.

I was threfore refused in another forum to register! But I didn't spammed a forum.

**Comment by psilocyberunner** [comment]
This repository is only a php-driven wrapper around a web-service of StopForumSpam. I'm not connected with any admin/developer of SFS web site.
